(()=>{
const XLSX_URL='https://cdn.jsdelivr.net/npm/xlsx-js-style@1.2.0/dist/xlsx.bundle.js';let loading;
const loadXLSX=()=>{if(window.XLSX)return Promise.resolve(window.XLSX);if(loading)return loading;loading=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=XLSX_URL;s.onload=()=>window.XLSX?resolve(window.XLSX):reject(Error('Biblioteca XLSX não carregou'));s.onerror=()=>reject(Error('Não foi possível carregar o gerador XLSX'));document.head.appendChild(s)});return loading};
const dt=v=>v?new Date(v).toLocaleDateString('pt-BR'):'-';const B={style:'thin',color:{rgb:'64748B'}};
const title={fill:{fgColor:{rgb:'0F172A'}},font:{name:'Aptos Display',sz:18,bold:true,color:{rgb:'FFFFFF'}},alignment:{horizontal:'center',vertical:'center'}};
const sub={fill:{fgColor:{rgb:'1E3A5F'}},font:{name:'Aptos',sz:10,bold:true,color:{rgb:'FFFFFF'}},alignment:{horizontal:'center',vertical:'center'}};
const head={fill:{fgColor:{rgb:'2563EB'}},font:{name:'Aptos',sz:10,bold:true,color:{rgb:'FFFFFF'}},alignment:{horizontal:'center',vertical:'center',wrapText:true},border:{top:B,bottom:B,left:B,right:B}};
const cell={font:{name:'Aptos',sz:10,color:{rgb:'0F172A'}},alignment:{vertical:'center',wrapText:true},border:{top:B,bottom:B,left:B,right:B}};
const alt={fill:{fgColor:{rgb:'EFF6FF'}},font:{name:'Aptos',sz:10,color:{rgb:'0F172A'}},alignment:{vertical:'center',wrapText:true},border:{top:B,bottom:B,left:B,right:B}};
const label={fill:{fgColor:{rgb:'DBEAFE'}},font:{name:'Aptos',sz:10,bold:true,color:{rgb:'0F172A'}},alignment:{horizontal:'center',vertical:'center',wrapText:true},border:{top:B,bottom:B,left:B,right:B}};
const value={fill:{fgColor:{rgb:'FFFFFF'}},font:{name:'Aptos',sz:18,bold:true,color:{rgb:'1D4ED8'}},alignment:{horizontal:'center',vertical:'center'},border:{top:B,bottom:B,left:B,right:B}};
function val(v){if(v==null)return '';if(typeof v==='object')return v.name||v.label||v.value||v.codigo||'';return v}function list(v){if(!v)return[];if(Array.isArray(v))return v;return Object.keys(v).map(k=>{const x=v[k]||{};if(typeof x==='object'&&!x.id)x.__key=k;return x})}
function sr(X,w,r,s){const q=X.utils.decode_range(r);for(let R=q.s.r;R<=q.e.r;R++)for(let C=q.s.c;C<=q.e.c;C++){const a=X.utils.encode_cell({r:R,c:C});w[a]??={v:''};w[a].s=s}}
function body(X,w,f,l,n){for(let r=f;r<=l;r++)sr(X,w,`A${r}:${X.utils.encode_col(n-1)}${r}`,r%2?cell:alt)}
function setup(w){w['!pageSetup']={orientation:'landscape',fitToWidth:1,fitToHeight:0};w['!margins']={left:.3,right:.3,top:.5,bottom:.5,header:.2,footer:.2}}
function os(X,o){const a=[['REGISTRO DE ORDENS DE SERVIÇO DE MANUTENÇÃO'],['HISTÓRICO • PLATAFORMA MANUTENÇÃO 4.0'],[],['Nº OS','Data Abertura','Equipamento','Setor','Tipo','Prioridade','Descrição / Serviço','Técnico','Data Prevista','Data Conclusão','Custo Peças (R$)','Custo M.O. (R$)','Custo Total (R$)','Status','Dispositivo']];list(o).sort((x,y)=>(x.createdAt||x.date||0)-(y.createdAt||y.date||0)).forEach(v=>{v=v||{};const id=val(v.id||v.orderId||v.osId||v.__key);a.push(['OS-'+String(id).slice(-8).toUpperCase(),dt(v.createdAt||v.openedAt||v.date),val(v.equipment||v.equipmentName||v.asset||v.assetName),val(v.sector||v.location),val(v.type||v.interventionType),val(v.priority),val(v.description||v.diagnosis||v.event),val(v.technician||v.responsible||v.createdByDevice),dt(v.dueDate||v.scheduledAt||v.preventiveDate),dt(v.completedAt||v.closedAt||v.date),Number(v.partsCost||v.partCost||0),Number(v.laborCost||v.cost||0),Number(v.totalCost||v.cost||Number(v.partsCost||v.partCost||0)+Number(v.laborCost||0)),val(v.status)||'Concluída',val(v.createdByDevice||v.completedByDevice||v.device)])});const w=X.utils.aoa_to_sheet(a);w['!merges']=[{s:{r:0,c:0},e:{r:0,c:14}},{s:{r:1,c:0},e:{r:1,c:14}}];w['!rows']=[{hpt:32},{hpt:20},{hpt:8},{hpt:36}];w['!freeze']='C5';w['!autofilter']={ref:`A4:O${Math.max(4,a.length)}`};w['!cols']=[15,16,25,14,13,13,42,22,16,17,18,18,19,15,18].map(wch=>({wch}));w.A1.s=title;w.A2.s=sub;sr(X,w,'A4:O4',head);if(a.length>4)body(X,w,5,a.length,15);for(let r=5;r<=a.length;r++){['B','I','J'].forEach(c=>w[`${c}${r}`].z='dd/mm/yyyy');['K','L','M'].forEach(c=>w[`${c}${r}`].z='R$ #,##0.00')}setup(w);return w}
function eq(X,e){const a=[['PLANO DE MANUTENÇÃO PREVENTIVA DE EQUIPAMENTOS'],['CADASTRO DE ATIVOS • PLATAFORMA MANUTENÇÃO 4.0'],[],['Cód. Equipamento','Equipamento','Local','Horímetro','Limite Preventiva','Criticidade','Status']];list(e).forEach((v,i)=>{v=v||{};a.push([val(v.codigo||v.code||v.__key)||'EQ-'+String(i+1).padStart(3,'0'),val(v.nome||v.name),val(v.location||v.sector),Number(v.horimetro||0),Number(v.limite||v.preventiveLimit||0),val(v.criticidade||v.criticality),val(v.status)||'Operacional'])});const w=X.utils.aoa_to_sheet(a);w['!merges']=[{s:{r:0,c:0},e:{r:0,c:6}},{s:{r:1,c:0},e:{r:1,c:6}}];w['!rows']=[{hpt:32},{hpt:20},{hpt:8},{hpt:36}];w['!freeze']='C5';w['!autofilter']={ref:`A4:G${Math.max(4,a.length)}`};w['!cols']=[24,28,20,15,20,20,20].map(wch=>({wch}));w.A1.s=title;w.A2.s=sub;sr(X,w,'A4:G4',head);if(a.length>4)body(X,w,5,a.length,7);setup(w);return w}
function dash(X,o){const a=list(o),t=a.length,d=a.filter(v=>['concluída','concluida','completed'].includes(String(v.status||'').toLowerCase())).length,p=t-d,c=a.reduce((s,v)=>s+Number(v.partsCost||v.partCost||0)+Number(v.laborCost||v.cost||0),0),r=[['PAINEL EXECUTIVO DE MANUTENÇÃO 4.0'],['RESUMO DO HISTÓRICO DE ORDENS DE SERVIÇO'],[],['TOTAL DE OS','','OS CONCLUÍDAS','','OS ABERTAS','','CUSTO TOTAL',''],[t,'',d,'',p,'',c,'']];const w=X.utils.aoa_to_sheet(r);w['!merges']=[{s:{r:0,c:0},e:{r:0,c:7}},{s:{r:1,c:0},e:{r:1,c:7}},{s:{r:3,c:0},e:{r:3,c:1}},{s:{r:3,c:2},e:{r:3,c:3}},{s:{r:3,c:4},e:{r:3,c:5}},{s:{r:3,c:6},e:{r:3,c:7}},{s:{r:4,c:0},e:{r:4,c:1}},{s:{r:4,c:2},e:{r:4,c:3}},{s:{r:4,c:4},e:{r:4,c:5}},{s:{r:4,c:6},e:{r:4,c:7}}];w['!rows']=[{hpt:34},{hpt:20},{hpt:8},{hpt:28},{hpt:42}];w['!cols']=Array.from({length:8},()=>({wch:18}));w.A1.s=title;w.A2.s=sub;sr(X,w,'A4:H4',label);sr(X,w,'A5:H5',value);w.G5.z='R$ #,##0.00';setup(w);return w}
function mergeHistory(data){const orders=list(data.orders),by={};orders.forEach(o=>{if(o)by[String(o.id||o.__key||'')]=o});const hist=list(data.history);if(!hist.length)return orders;const result=hist.map(h=>{const id=String(h.orderId||h.osId||h.orderID||h.id||h.__key||'');return Object.assign({},by[id]||{},h,{id:id||by[id]?.id||by[id]?.__key})});orders.forEach(o=>{const id=String(o&&(o.id||o.__key)||'');if(id&&!result.some(h=>String(h.id||h.orderId||h.osId||h.__key||'')===id)&&['concluída','concluida','completed'].includes(String(o.status||'').toLowerCase()))result.push(o)});return result}
async function exportExcel(){const b=document.getElementById('exportXlsxBtn')||document.getElementById('exportExcelBtn');if(b){b.disabled=true;b.dataset.oldHtml=b.innerHTML;b.innerHTML='⏳ Gerando...'}try{const X=await loadXLSX();const snap=await firebase.database().ref('workshopCMMS').once('value');const data=snap.val()||{},rows=mergeHistory(data),wb=X.utils.book_new();X.utils.book_append_sheet(wb,dash(X,rows),'Painel Executivo');X.utils.book_append_sheet(wb,os(X,rows),'Ordens de Serviço');X.utils.book_append_sheet(wb,eq(X,data.equipments),'Preventivas');X.writeFile(wb,`gestao-manutencao-4.0-${new Date().toISOString().slice(0,10)}.xlsx`);if(window.fusionToast)window.fusionToast('Planilha profissional gerada com sucesso')}catch(e){console.error(e);alert('Não foi possível gerar a planilha: '+e.message)}finally{if(b){b.disabled=false;b.innerHTML=b.dataset.oldHtml||'📊 Exportar Excel formatado'}}}
function install(){const s=document.getElementById('historico');if(!s)return;const cs=[...document.querySelectorAll('button')].filter(x=>/exportar\s+(excel|csv|planilha)/i.test(x.textContent||''));const b=document.getElementById('exportXlsxBtn')||document.getElementById('exportExcelBtn')||cs[0];cs.forEach(x=>{if(x!==b)x.remove()});if(!b)return;if(!b.id)b.id='exportXlsxBtn';b.type='button';b.className='fusion-btn fb';b.textContent='📊 Exportar Excel formatado';b.onclick=exportExcel;const h=s.querySelector('h2');if(h&&h.parentNode){h.parentNode.classList.add('flex','justify-between','items-center','gap-3');if(b.parentElement!==h.parentNode)h.parentNode.appendChild(b)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();setInterval(install,1500);window.exportFormatted=exportExcel;
})();
