(function(){
'use strict';
/* Módulo isolado de exportação Excel. Nenhuma outra função do aplicativo é alterada. */
var CDN='https://cdn.jsdelivr.net/npm/xlsx-js-style@1.2.0/dist/xlsx.bundle.js',loading=null;
function loadXLSX(){
  if(window.XLSX&&window.XLSX.utils&&window.XLSX.write)return Promise.resolve(window.XLSX);
  if(loading)return loading;
  loading=new Promise(function(resolve,reject){
    var s=document.createElement('script');s.src=CDN;s.async=true;
    s.onload=function(){window.XLSX&&window.XLSX.utils&&window.XLSX.write?resolve(window.XLSX):reject(new Error('A biblioteca Excel não foi inicializada.'))};
    s.onerror=function(){reject(new Error('Não foi possível carregar a biblioteca Excel. Verifique a conexão com a internet.'))};
    document.head.appendChild(s);
  });
  return loading;
}
function value(v){if(v==null)return '';if(typeof v==='object')return v.name||v.label||v.value||v.description||v.codigo||'';return v}
function date(v){if(v==null||v==='')return '';var d=new Date(v);return isNaN(d.getTime())?value(v):d.toLocaleString('pt-BR')}
function list(v){if(!v)return [];if(Array.isArray(v))return v;return Object.keys(v).map(function(k){var x=v[k]||{};if(typeof x==='object'&&!Array.isArray(x))x=Object.assign({__key:k},x);return x})}
function id(v){return String(v&&(v.id||v.orderId||v.osId||v.orderID||v.__key)||'')}
function completed(v){var s=String(value(v&&v.status)||'').toLowerCase().trim();return ['concluída','concluida','concluído','concluido','completed','finalizada','finalizado','encerrada','encerrado'].indexOf(s)>=0}
function getData(){if(window.firebase&&firebase.database)return firebase.database().ref('workshopCMMS').once('value').then(function(s){return s.val()||{}}).catch(function(){return window.cmmsState||{}});return Promise.resolve(window.cmmsState||{})}
function historyRows(data){var orders=list(data.orders),history=list(data.history),by={},seen={},out=[];orders.forEach(function(o){var k=id(o);if(k)by[k]=o});history.forEach(function(h){var k=String(h&&((h.orderId||h.osId||h.orderID||h.id||h.__key)||''));var r=Object.assign({},by[k]||{},h||{});if(k)r.id=k;var key=k||'h'+out.length;if(!seen[key]){seen[key]=1;out.push(r)}});orders.forEach(function(o){if(!completed(o))return;var k=id(o),key=k||'o'+out.length;if(!seen[key]){seen[key]=1;out.push(o)}});out.sort(function(a,b){return (new Date(b.completedAt||b.closedAt||b.createdAt||b.date||0).getTime()||0)-(new Date(a.completedAt||a.closedAt||a.createdAt||a.date||0).getTime()||0)});return out}
function makeOS(rows){return rows.map(function(v){return {'Nº OS':value(v.orderNumber||v.osNumber||v.orderId||v.osId||v.id||v.__key),'Data Abertura':date(v.createdAt||v.openedAt||v.openDate||v.date),'Equipamento':value(v.equipment||v.equipmentName||v.asset||v.assetName),'Localização':value(v.location||v.sector||v.area),'Tipo':value(v.type||v.interventionType||v.maintenanceType),'Prioridade':value(v.priority),'Descrição / Serviço':value(v.description||v.service||v.event||v.diagnosis),'Técnico':value(v.technician||v.responsible||v.assignedTo||v.createdByDevice),'Data Prevista':date(v.dueDate||v.scheduledAt||v.preventiveDate||v.scheduledDate),'Data Conclusão':date(v.completedAt||v.closedAt||v.completionDate),'Custo Peças (R$)':Number(v.partsCost!=null?v.partsCost:(v.partCost!=null?v.partCost:0))||0,'Custo M.O. (R$)':Number(v.laborCost!=null?v.laborCost:(v.laborCostBRL!=null?v.laborCostBRL:0))||0,'Custo Total (R$)':Number(v.totalCost!=null?v.totalCost:(v.cost!=null?v.cost:Number(v.partsCost||v.partCost||0)+Number(v.laborCost||0)))||0,'Status':value(v.status)||'Concluída','Peça Utilizada':value(v.partName||v.part||v.usedPart||v.partUsed),'Quantidade da Peça':Number(v.partQuantity!=null?v.partQuantity:(v.quantityUsed!=null?v.quantityUsed:(v.usedQuantity!=null?v.usedQuantity:0)))||0,'Observações':value(v.notes||v.observations||v.comments),'Dispositivo':value(v.device||v.completedByDevice||v.createdByDevice)}})}
function makeAssets(items){return list(items).map(function(v){return {'Código':value(v.codigo||v.code||v.tag||v.__key),'Equipamento':value(v.nome||v.name),'Tipo / Modelo':value(v.type||v.model),'Fabricante':value(v.manufacturer),'Localização':value(v.location||v.sector),'Horímetro':Number(v.horimetro!=null?v.horimetro:0)||0,'Criticidade':value(v.criticality||v.criticidade),'Status':value(v.status),'Limite Preventiva':Number(v.preventiveLimit!=null?v.preventiveLimit:(v.limite!=null?v.limite:0))||0}})}
function border(c){return{top:{style:'thin',color:{rgb:c}},bottom:{style:'thin',color:{rgb:c}},left:{style:'thin',color:{rgb:c}},right:{style:'thin',color:{rgb:c}}}}
function formatSheet(X,ws,title){
  var rows=X.utils.sheet_to_json(ws,{header:1,raw:true,defval:''});if(!rows.length)return ws;
  var headers=rows[0]||[],body=rows.slice(1);var data=[[title],headers].concat(body);ws=X.utils.aoa_to_sheet(data);
  var lastCol=headers.length-1,lastRow=data.length-1;ws['!merges']=[{s:{r:0,c:0},e:{r:0,c:lastCol}}];ws['!freeze']={xSplit:0,ySplit:2};ws['!autofilter']={ref:X.utils.encode_range({s:{r:1,c:0},e:{r:lastRow,c:lastCol}})};ws['!pageSetup']={orientation:'landscape',fitToWidth:1,fitToHeight:0,paperSize:9};ws['!margins']={left:.25,right:.25,top:.35,bottom:.35,header:.15,footer:.15};ws['!rows']=[{hpt:42},{hpt:36}];for(var rr=2;rr<=lastRow;rr++)ws['!rows'][rr]={hpt:30};
  var blue='4F6B9A',teal='36575D',teal2='456B72',light='E8F0F1',white='FFFFFF',grid='B8C1C3',text='263238';
  function cell(r,c){var a=X.utils.encode_cell({r:r,c:c});if(!ws[a])ws[a]={t:'s',v:''};return ws[a]}
  cell(0,0).s={fill:{patternType:'solid',fgColor:{rgb:'F3F3F3'}},font:{name:'Aptos Display',sz:24,bold:true,color:{rgb:blue}},alignment:{horizontal:'left',vertical:'center'},border:{bottom:{style:'medium',color:{rgb:blue)}}};
  for(var c=0;c<=lastCol;c++){cell(1,c).s={fill:{patternType:'solid',fgColor:{rgb:teal2}},font:{name:'Aptos',sz:10,bold:true,color:{rgb:white}},alignment:{horizontal:'center',vertical:'center',wrapText:true},border:border(grid)};for(var r=2;r<=lastRow;r++){var dc=cell(r,c),h=headers[c]||'';dc.s={fill:{patternType:'solid',fgColor:{rgb:r%2===0?'FFFFFF':light}},font:{name:'Aptos',sz:10,color:{rgb:text}},alignment:{horizontal:typeof dc.v==='number'?'center':'left',vertical:'center',wrapText:true},border:border(grid)};if(typeof dc.v==='number'&&/Custo/.test(h))dc.s.numFmt='R$ #,##0.00';if(typeof dc.v==='number'&&/(Quantidade|Horímetro|Limite)/.test(h))dc.s.numFmt='#,##0.00'}}
  ws['!cols']=headers.map(function(h,i){var max=Math.max(12,String(h).length+3);for(var r=2;r<=lastRow;r++)max=Math.max(max,String(cell(r,i).v==null?'':cell(r,i).v).length+2);if(/Descrição|Observações/.test(h))max=Math.max(max,36);if(/Equipamento|Técnico|Fabricante/.test(h))max=Math.max(max,24);if(/Data/.test(h))max=Math.max(max,18);return{wch:Math.min(42,max)}});
  return ws;
}
function makeSheet(X,rows,title){var ws=X.utils.json_to_sheet(rows.length?rows:[{}]);return formatSheet(X,ws,title)}
function download(X,wb,name){var out=X.write(wb,{bookType:'xlsx',type:'array',compression:true});var blob=new Blob([out],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});var url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.style.display='none';document.body.appendChild(a);a.click();setTimeout(function(){if(a.parentNode)a.parentNode.removeChild(a);URL.revokeObjectURL(url)},1500)}
window.exportarExcelFormatado=async function(){var b=document.getElementById('exportExcelBtn')||document.getElementById('exportXlsxBtn'),old=b?b.innerHTML:'';try{if(b){b.disabled=true;b.innerHTML='⏳ Preparando planilha...'}var X=await loadXLSX(),data=await getData(),os=makeOS(historyRows(data));if(!os.length)os=[{'Nº OS':'','Data Abertura':'','Equipamento':'','Localização':'','Tipo':'','Prioridade':'','Descrição / Serviço':'Nenhuma O.S. registrada no histórico','Técnico':'','Data Prevista':'','Data Conclusão':'','Custo Peças (R$)':0,'Custo M.O. (R$)':0,'Custo Total (R$)':0,'Status':'','Peça Utilizada':'','Quantidade da Peça':0,'Observações':'','Dispositivo':''}];var wb=X.utils.book_new();X.utils.book_append_sheet(wb,makeSheet(X,os,'RELATÓRIO DE MANUTENÇÃO — HISTÓRICO DE ORDENS DE SERVIÇO'),'Histórico de O.S.');var assets=makeAssets(data.equipments);if(assets.length)X.utils.book_append_sheet(wb,makeSheet(X,assets,'REGISTRO DE ATIVOS — EQUIPAMENTOS'),'Ativos');download(X,wb,'Relatorio_Manutencao_Historico_'+new Date().toISOString().slice(0,10)+'.xlsx');if(window.fusionToast)window.fusionToast('Planilha do histórico exportada com sucesso')}catch(e){console.error('Exportação Excel:',e);alert('Não foi possível exportar o histórico: '+(e&&e.message?e.message:String(e)))}finally{if(b){b.disabled=false;b.innerHTML=old||'<i class="fa-solid fa-file-excel mr-2"></i>Exportar Excel'}}};
/* Pré-carrega sem bloquear a inicialização do aplicativo. */
loadXLSX().catch(function(e){console.warn('Biblioteca Excel será carregada ao clicar em Exportar.',e)});
})();
