(()=>{
  const XLSX_URL='https://cdn.jsdelivr.net/npm/xlsx-js-style@1.2.0/dist/xlsx.bundle.js';let loading;
  const loadXLSX=()=>{if(window.XLSX)return Promise.resolve(window.XLSX);if(loading)return loading;loading=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=XLSX_URL;s.onload=()=>window.XLSX?resolve(window.XLSX):reject(Error('Biblioteca XLSX não carregou'));s.onerror=()=>reject(Error('Não foi possível carregar o gerador XLSX'));document.head.appendChild(s)});return loading};
  const dt=v=>v?new Date(v).toLocaleDateString('pt-BR'):'-';const border={style:'thin',color:{rgb:'D9D9D9'}};const styles={title:{fill:{fgColor:{rgb:'1F4E79'}},font:{color:{rgb:'FFFFFF'},bold:true,sz:14},alignment:{horizontal:'center',vertical:'center'}},header:{fill:{fgColor:{rgb:'2F5597'}},font:{color:{rgb:'FFFFFF'},bold:true},alignment:{horizontal:'center',vertical:'center',wrapText:true},border:{top:border,bottom:border,left:border,right:border}},cell:{alignment:{vertical:'center',wrapText:true},border:{top:border,bottom:border,left:border,right:border}},kpiLabel:{fill:{fgColor:{rgb:'EDF2F8'}},font:{color:{rgb:'595959'},bold:true},alignment:{horizontal:'center',vertical:'center',wrapText:true},border:{top:border,bottom:border,left:border,right:border}},kpiValue:{fill:{fgColor:{rgb:'EDF2F8'}},font:{color:{rgb:'1F4E79'},bold:true,sz:14},alignment:{horizontal:'center',vertical:'center'},border:{top:border,bottom:border,left:border,right:border}}};
  function sr(X,w,r,s){const q=X.utils.decode_range(r);for(let R=q.s.r;R<=q.e.r;R++)for(let C=q.s.c;C<=q.e.c;C++){const a=X.utils.encode_cell({r:R,c:C});w[a]??={v:''};w[a].s=s}}
  function os(X,o){const a=[['REGISTRO DE ORDENS DE SERVIÇO DE MANUTENÇÃO'],[],['Nº OS','Data Abertura','Equipamento','Setor','Tipo','Prioridade','Descrição da Falha / Serviço','Técnico Responsável','Data Prevista','Data Conclusão','Custo Peças (R$)','Custo M.O. (R$)','Custo Total (R$)','Status']];Object.entries(o||{}).sort((x,y)=>(x[1].createdAt||0)-(y[1].createdAt||0)).forEach(([id,v])=>a.push(['OS-'+id.slice(-8).toUpperCase(),dt(v.createdAt),v.equipment||'-',v.sector||'-',v.type||'-',v.priority||'-',v.description||'-',v.technician||v.createdByDevice||'-',dt(v.dueDate),dt(v.completedAt),Number(v.partsCost||0),Number(v.laborCost||v.cost||0),Number(v.partsCost||0)+Number(v.laborCost||v.cost||0),v.status||'Pendente']));const w=X.utils.aoa_to_sheet(a);w['!merges']=[{s:{r:0,c:0},e:{r:0,c:13}}];w['!freeze']='C4';w['!autofilter']={ref:`A3:N${Math.max(3,a.length)}`};w['!cols']=[46,16,26,13,13,13,38,23,16,17,19,18,19,15].map(w=>({wch:w}));w.A1.s=styles.title;sr(X,w,`A3:N${Math.max(3,a.length)}`,styles.cell);sr(X,w,'A3:N3',styles.header);for(let r=4;r<=a.length;r++){w[`B${r}`].z='dd/mm/yyyy';w[`I${r}`].z='dd/mm/yyyy';w[`J${r}`].z='dd/mm/yyyy';w[`K${r}`].z='R$ #,##0.00';w[`L${r}`].z='R$ #,##0.00';w[`M${r}`].z='R$ #,##0.00'}return w}
  function eq(X,e){const a=[['PLANO DE MANUTENÇÃO PREVENTIVA DE EQUIPAMENTOS'],[],['Cód. Equipamento','Equipamento','Setor','Frequência','Última Realizada','Próxima Agendada','Responsável','Status do Plano']];Object.entries(e||{}).forEach(([id,v],i)=>a.push([v.code||'EQ-'+String(i+1).padStart(3,'0'),v.name||'-',v.sector||v.location||'-',v.frequency||'Mensal',dt(v.lastMaintenance),dt(v.nextMaintenance),v.responsible||v.createdByDevice||'-',v.planStatus||v.status||'Em Dia']));const w=X.utils.aoa_to_sheet(a);w['!merges']=[{s:{r:0,c:0},e:{r:0,c:7}}];w['!freeze']='C4';w['!autofilter']={ref:`A3:H${Math.max(3,a.length)}`};w['!cols']=[50,24,14,14,20,20,24,25].map(w=>({wch:w}));w.A1.s=styles.title;sr(X,w,`A3:H${Math.max(3,a.length)}`,styles.cell);sr(X,w,'A3:H3',styles.header);return w}
  function dash(X,o){const a=Object.values(o||{}),t=a.length,d=a.filter(v=>v.status==='Concluída').length,p=t-d,c=a.reduce((s,v)=>s+Number(v.partsCost||0)+Number(v.laborCost||v.cost||0),0),r=[['PAINEL DE CONTROLE DE MANUTENÇÃO E INDICADORES (KPIs)'],[],['TOTAL DE ORDENS DE SERVIÇO','','OS CONCLUÍDAS','','OS EM ANDAMENTO / PENDENTE','','CUSTO TOTAL DE MANUTENÇÃO',''],[t,'',d,'',p,'',c,'']];const w=X.utils.aoa_to_sheet(r);w['!merges']=[{s:{r:0,c:0},e:{r:0,c:7}},{s:{r:2,c:0},e:{r:2,c:1}},{s:{r:2,c:2},e:{r:2,c:3}},{s:{r:2,c:4},e:{r:2,c:5}},{s:{r:2,c:6},e:{r:2,c:7}},{s:{r:3,c:0},e:{r:4,c:1}},{s:{r:3,c:2},e:{r:4,c:3}},{s:{r:3,c:4},e:{r:4,c:5}},{s:{r:3,c:6},e:{r:4,c:7}}];w['!cols']=Array.from({length:8},()=>({wch:18}));w.A1.s=styles.title;sr(X,w,'A3:H3',styles.kpiLabel);sr(X,w,'A4:H5',styles.kpiValue);w.G4.z='R$ #,##0.00';return w}
  function wb(){const X=window.XLSX;let S={};try{S=(typeof state!=='undefined'?state:{})}catch(e){}const b=X.utils.book_new();X.utils.book_append_sheet(b,dash(X,S.orders),'Painel de Controle');X.utils.book_append_sheet(b,os(X,S.orders),'Ordens de Serviço');X.utils.book_append_sheet(b,eq(X,S.equipments),'Plano de Preventivas');return b}
  async function exportExcel(){const b=document.getElementById('exportXlsxBtn');if(b){b.disabled=true;b.textContent='Gerando...'}try{const X=await loadXLSX();X.writeFile(wb(),`gestao-manutencao-${new Date().toISOString().slice(0,10)}.xlsx`)}catch(e){console.error(e);alert('Não foi possível gerar a planilha Excel formatada.')}finally{if(b){b.disabled=false;b.textContent='📊 Exportar Excel formatado'}}}
  function install(){const s=document.getElementById('historico');if(!s)return;/* remove botões antigos/duplicados sem alterar o layout base */document.querySelectorAll('button').forEach(x=>{if(x.id!=='exportXlsxBtn'&&/exportar\s+(excel|csv|planilha)/i.test(x.textContent||''))x.remove()});const h=s.querySelector('h2');if(!h)return;let b=document.getElementById('exportXlsxBtn');if(!b){b=document.createElement('button');b.id='exportXlsxBtn';b.type='button';b.className='bg-blue-600 hover:bg-blue-500 rounded-lg px-3 py-2 text-xs font-bold';b.textContent='📊 Exportar Excel formatado';b.onclick=exportExcel;h.parentNode.classList.add('flex','justify-between','items-center','gap-3');h.parentNode.appendChild(b)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();setInterval(install,1500);window.exportFormatted=exportExcel;
})();
