(function(){
'use strict';
function loadXLSX(){return new Promise(function(resolve,reject){if(window.XLSX)return resolve(window.XLSX);var s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=function(){resolve(window.XLSX)};s.onerror=function(){reject(new Error('Não foi possível carregar o módulo Excel.'))};document.head.appendChild(s)})}
function value(v){return v==null?'':(typeof v==='object'?(v.name||v.label||v.value||''):v)}
function date(v){if(!v)return '';var d=new Date(v);return isNaN(d.getTime())?value(v):d.toLocaleString('pt-BR')}
function list(v){if(!v)return [];if(Array.isArray(v))return v;return Object.keys(v).map(function(k){var x=v[k]||{};if(typeof x==='object'&&!x.id)x.__key=k;return x})}
window.exportarExcelFormatado=async function(){try{
var XLSX=await loadXLSX(),state=window.cmmsState||{},orders=state.orders||{},history=state.history||{},equipments=state.equipments||{},rows=[],orderList=list(orders),historyList=list(history),orderById={};
orderList.forEach(function(o){if(o)orderById[String(o.id||o.__key||'')]=o});
historyList.forEach(function(h){if(!h)return;var oid=String(h.orderId||h.osId||h.orderID||h.id||h.__key||''),o=orderById[oid]||{};rows.push({'OS':value(h.orderId||h.osId||h.orderID||o.id||h.__key),'Equipamento':value(h.equipment||h.equipmentName||o.equipment||o.asset||o.assetName),'Tipo':value(h.type||h.interventionType||o.type||o.interventionType),'Técnico':value(h.technician||h.responsible||o.technician||o.responsible),'Categoria da Falha':value(h.failureCategory||h.failure||o.failureCategory||o.failure),'Peça':value(h.partName||h.part||o.partName||o.part),'Status':value(h.status||o.status||'Concluída'),'Tempo de Parada (min)':value(h.downtimeMinutes||h.downtime||o.downtimeMinutes||o.downtime),'Custo Mão de Obra (R$)':Number(h.laborCost!=null?h.laborCost:(o.laborCost||0)),'Custo da Peça (R$)':Number(h.partCost!=null?h.partCost:(o.partCost||0)),'Custo Total (R$)':Number(h.cost!=null?h.cost:(o.cost||h.totalCost||0)),'Descrição / Diagnóstico':value(h.description||h.diagnosis||h.event||o.description||o.diagnosis),'Criada em':date(h.createdAt||o.createdAt),'Concluída em':date(h.completedAt||h.date||o.completedAt),'Dispositivo':value(h.device||h.completedByDevice||o.createdByDevice||o.completedByDevice)});});
orderList.forEach(function(o){if(!o)return;var status=String(o.status||'').toLowerCase(),done=status==='concluída'||status==='concluida'||status==='completed';if(!done)return;var oid=String(o.id||o.__key||'');if(rows.some(function(r){return oid&&String(r.OS||'')===oid}))return;rows.push({'OS':value(o.id||o.__key),'Equipamento':value(o.equipment||o.asset||o.assetName),'Tipo':value(o.type||o.interventionType),'Técnico':value(o.technician||o.responsible),'Categoria da Falha':value(o.failureCategory||o.failure),'Peça':value(o.partName||o.part),'Status':value(o.status),'Tempo de Parada (min)':value(o.downtimeMinutes||o.downtime),'Custo Mão de Obra (R$)':Number(o.laborCost||0),'Custo da Peça (R$)':Number(o.partCost||0),'Custo Total (R$)':Number(o.cost||0),'Descrição / Diagnóstico':value(o.description||o.diagnosis),'Criada em':date(o.createdAt),'Concluída em':date(o.completedAt),'Dispositivo':value(o.createdByDevice||o.completedByDevice)});});
if(!rows.length)rows.push({'OS':'','Equipamento':'','Tipo':'','Técnico':'','Categoria da Falha':'','Peça':'','Status':'','Tempo de Parada (min)':'','Custo Mão de Obra (R$)':0,'Custo da Peça (R$)':0,'Custo Total (R$)':0,'Descrição / Diagnóstico':'Nenhuma O.S. registrada','Criada em':'','Concluída em':'','Dispositivo':''});
var ws=XLSX.utils.json_to_sheet(rows),widths=[12,28,16,22,24,25,18,20,23,22,20,45,22,22,20];ws['!cols']=widths.map(function(w){return{wch:w}});var range=XLSX.utils.decode_range(ws['!ref']);for(var c=range.s.c;c<=range.e.c;c++){var cell=ws[XLSX.utils.encode_cell({r:0,c:c})];if(cell)cell.s={font:{bold:true,color:{rgb:'FFFFFF'}},fill:{fgColor:{rgb:'1D4ED8'}},alignment:{horizontal:'center',vertical:'center'}}}ws['!autofilter']={ref:ws['!ref']};ws['!freeze']={xSplit:0,ySplit:1};var wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Ordens de Serviço');
var eqRows=list(equipments).map(function(e){e=e||{};return{'Código':value(e.code||e.tag||e.__key),'Equipamento':value(e.name),'Tipo / Modelo':value(e.type||e.model),'Fabricante':value(e.manufacturer),'Localização':value(e.location),'Horímetro':value(e.horimetro),'Criticidade':value(e.criticality||e.criticidade),'Status':value(e.status),'Limite Preventiva':value(e.preventiveLimit)}});if(eqRows.length){var we=XLSX.utils.json_to_sheet(eqRows);we['!cols']=[{wch:20},{wch:30},{wch:25},{wch:24},{wch:24},{wch:14},{wch:18},{wch:18},{wch:20}];var er=XLSX.utils.decode_range(we['!ref']);for(var ec=er.s.c;ec<=er.e.c;ec++){var eh=we[XLSX.utils.encode_cell({r:0,c:ec})];if(eh)eh.s={font:{bold:true,color:{rgb:'FFFFFF'}},fill:{fgColor:{rgb:'1D4ED8'}},alignment:{horizontal:'center'}}}we['!autofilter']={ref:we['!ref']};we['!freeze']={xSplit:0,ySplit:1};XLSX.utils.book_append_sheet(wb,we,'Ativos')}
var stamp=new Date().toISOString().slice(0,10).replace(/-/g,'');XLSX.writeFile(wb,'Relatorio_Manutencao_'+stamp+'.xlsx')}catch(err){console.error('Exportação Excel:',err);alert('Não foi possível gerar a planilha. Verifique sua conexão com a internet e tente novamente.')}};window.exportarCSV=function(){return window.exportarExcelFormatado()};
})();
