(()=>{
 const XLSX_URL='https://cdn.jsdelivr.net/npm/xlsx-js-style@1.2.0/dist/xlsx.bundle.js';let loading;
 const loadXLSX=()=>{if(window.XLSX)return Promise.resolve(window.XLSX);if(loading)return loading;loading=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=XLSX_URL;s.onload=()=>window.XLSX?resolve(window.XLSX):reject(Error('Biblioteca XLSX não carregou'));s.onerror=()=>reject(Error('Não foi possível carregar o gerador XLSX'));document.head.appendChild(s)});return loading};
 const dt=v=>v?new Date(v).toLocaleDateString('pt-BR'):'-';
 const border={style:'thin',color:{rgb:'CBD5E1'}};
 const styles={title:{fill:{fgColor:{rgb:'1D4ED8'}},font:{color:{rgb:'FFFFFF'},bold:true,sz:15},alignment:{horizontal:'center',vertical:'center'}},header:{fill:{fgColor:{rgb:'0F172A'}},font:{color:{rgb:'FFFFFF'},bold:true},alignment:{horizontal:'center',vertical:'center',wrapText:true},border:{top:border,bottom:border,left:border,right:border}},cell:{alignment:{vertical:'center',wrapText:true},border:{top:border,bottom:border,left:border,right:border}},kpiLabel:{fill:{fgColor:{rgb:'E2E8F0'}},font:{color:{rgb:'334155'},bold:true},alignment:{horizontal:'center',vertical:'center',wrapText:true},border:{top:border,bottom:border,left:border,right:border}},kpiValue:{fill:{fgColor:{rgb:'F8FAFC'}},font:{color:{rgb:'1D4ED8'},bold:true,sz:16},alignment:{horizontal:'center',vertical:'center'},border:{top:border,bottom:border,left:border,right:border}}};
 function sr(X,w,r,s){const q=X.utils.decode_range(r);for(let R=q.s.r;R<=q.e.r;R++)for(let C=q.s.c;C<=q.e.c;C++){const a=X.utils.encode_cell({r:R,c:C});w[a]??={v:''};w[a].s=s}}
 function val(v){if(v==null)return '';if(typeof v==='object')return v.name||v.label||v.value||'';return v}
 function list(v){if(!v)return [];if(Array.isArray(v))return v;return Object.keys(v).map(k=>{const x=v[k]||{};if(typeof x==='object'&&!x.id)x.__key=k;return x})}
 function os(X,o){const a=[['REGISTRO DE ORDENS DE SERVIÇO DE MANUTENÇÃO'],[],['Nº OS','Data Abertura','Equipamento','Setor','Tipo','Prioridade','Descrição / Serviço','Técnico','Data Prevista','Data Conclusão','Custo Peças (R$)','Custo M.O. (R$)','Custo Total (R$)','Status','Dispositivo']];list(o).sort((x,y)=>(x.createdAt||x.date||0)-(y.createdAt||y.date||0)).forEach(v=>{v=v||{};const id=val(v.id||v.orderId||v.osId||v.__key);a.push(['OS-'+String(id).slice(-8).toUpperCase(),dt(v.createdAt||v.openedAt||v.date),val(v.equipment||v.equipmentName||v.asset||v.assetName),val(v.sector||v.location),val(v.type||v.interventionType),val(v.priority),val(v.description||v.diagnosis||v.event),val(v.technician||v.responsible||v.createdByDevice),dt(v.dueDate||v.scheduledAt||v.preventiveDate),dt(v.completedAt||v.closedAt||v.date),Number(v.partsCost||v.partCost||0),Number(v.laborCost||v.cost||0),Number(v.totalCost||v.cost||Number(v.partsCost||v.partCost||0)+Number(v.laborCost||0)),val(v.status)||'Concluída',val(v.createdByDevice||v.completedByDevice||v.device)])});const w=X.utils.aoa_to_sheet(a);w['!merges']=[{s:{r:0,c:0},e:{r:0,c:14}}];w['!freeze']='C4';w['!autofilter']={ref:`A3:O${Math.max(3,a.length)}`};w['!cols']=[15,16,25,14,13,13,42,22,16,17,18,18,19,15,18].map(v=>({wch:v}));w.A1.s=styles.title;sr(X,w,`A3:O${Math.max(3,a.length)}`,styles.cell);sr(X,w,'A3:O3',styles.header);for(let r=4;r<=a.length;r++){['B','I','J'].forEach(c=>w[`${c}${r}`].z='dd/mm/yyyy');['K','L','M'].forEach(c=>w[`${c}${r}`].z='R$ #,##0.00')}return w}
 function eq(X,e){const a=[['PLANO DE MANUTENÇÃO PREVENTIVA DE EQUIPAMENTOS'],[],['Cód. Equipamento','Equipamento','Local','Horímetro','Limite Preventiva','Criticidade','Status']];list(e).forEach((v,i)=>{v=v||{};a.push([val(v.codigo||v.code||v.__key)||'EQ-'+String(i+1).padStart(3,'0'),val(v.nome||v.name),val(v.location||v.sector),Number(v.horimetro||0),Number(v.limite||v.preventiveLimit||0),val(v.criticidade||v.criticality),val(v.status)||'Operacional'])});const w=X.utils.aoa_to_sheet(a);w['!merges']=[{s:{r:0,c:0},e:{r:0,c:6}}];w['!freeze']='C4';w['!autofilter']={ref:`A3:G${Math.max(3,a.length)}`};w['!cols']=[24,28,20,15,20,20,20].map(v=>({wch:v}));w.A1.s=styles.title;sr(X,w,`A3:G${Math.max(3,a.length)}`,styles.cell);sr(X,w,'A3:G3',styles.header);return w}
 function dash(X,o){const a=list(o),t=a.length,d=a.filter(v=>{const s=String(v.status||'').toLowerCase();return s==='concluída'||s==='concluida'||s==='completed'}).length,p=t-d,c=a.reduce((s,v)=>s+Number(v.partsCost||v.partCost||0)+Number(v.laborCost||v.cost||0),0),r=[['PAINEL DE CONTROLE DE MANUTENÇÃO 4.0'],[],['TOTAL DE OS','','OS CONCLUÍDAS','','OS ABERTAS','','CUSTO TOTAL',''],[t,'',d,'',p,'',c,'']];const w=X.utils.aoa_to_sheet(r);w['!merges']=[{s:{r:0,c:0},e:{r:0,c:7}},{s:{r:2,c:0},e:{r:2,c:1}},{s:{r:2,c:2},e:{r:2,c:3}},{s:{r:2,c:4},e:{r:2,c:5}},{s:{r:2,c:6},e:{r:2,c:7}}];w['!cols']=Array.from({length:8},()=>({wch:18}));w.A1.s=styles.title;sr(X,w,'A3:H3',styles.kpiLabel);sr(X,w,'A4:H4',styles.kpiValue);w.G4.z='R$ #,##0.00';return w}
 function mergeHistory(data){const orders=list(data.orders),byId={};orders.forEach(o=>{if(o)byId[String(o.id||o.__key||'')]=o});const hist=list(data.history);if(!hist.length)return orders;const result=hist.map(h=>{const id=String(h.orderId||h.osId||h.orderID||h.id||h.__key||'');const o=byId[id]||{};return Object.assign({},o,h,{id:id||o.id||o.__key})});orders.forEach(o=>{const id=String(o&&(o.id||o.__key)||'');if(id&&!result.some(h=>String(h.id||h.orderId||h.osId||h.__key||'')===id)){const s=String(o.status||'').toLowerCase();if(s==='concluída'||s==='concluida'||s==='completed')result.push(o)}});return result}
 async function exportExcel(){const b=document.getElementById('exportXlsxBtn')||document.getElementById('exportExcelBtn');if(b){b.disabled=true;b.dataset.oldHtml=b.innerHTML;b.innerHTML='⏳ Gerando...'}try{const X=await loadXLSX();const snap=await firebase.database().ref('workshopCMMS').once('value');const data=snap.val()||{};const historyRows=mergeHistory(data);const wb=X.utils.book_new();X.utils.book_append_sheet(wb,dash(X,historyRows),'Painel de Controle');X.utils.book_append_sheet(wb,os(X,historyRows),'Ordens de Serviço');X.utils.book_append_sheet(wb,eq(X,data.equipments),'Plano de Preventivas');X.writeFile(wb,`gestao-manutencao-4.0-${new Date().toISOString().slice(0,10)}.xlsx`);if(window.fusionToast)window.fusionToast('Excel formatado gerado com sucesso')}catch(e){console.error(e);alert('Não foi possível gerar a planilha Excel formatada: '+e.message)}finally{if(b){b.disabled=false;b.innerHTML=b.dataset.oldHtml||'📊 Exportar Excel formatado'}}}
 function install(){const s=document.getElementById('historico');if(!s)return;const candidates=[...document.querySelectorAll('button')].filter(x=>/exportar\s+(excel|csv|planilha)/i.test(x.textContent||''));const b=document.getElementById('exportXlsxBtn')||document.getElementById('exportExcelBtn')||candidates[0];candidates.forEach(x=>{if(x!==b)x.remove()});if(!b)return;if(!b.id)b.id='exportXlsxBtn';b.type='button';b.className='fusion-btn fb';b.textContent='📊 Exportar Excel formatado';b.onclick=exportExcel;const h=s.querySelector('h2');if(h&&h.parentNode){h.parentNode.classList.add('flex','justify-between','items-center','gap-3');if(b.parentElement!==h.parentNode)h.parentNode.appendChild(b)}}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();setInterval(install,1500);window.exportFormatted=exportExcel;
})();
