(()=>{
  const q=id=>document.getElementById(id), R=firebase.database().ref('workshopCMMS');
  const D=localStorage.getItem('cmmsDeviceId')||'DEV-'+Math.random().toString(36).slice(2,10).toUpperCase(); localStorage.setItem('cmmsDeviceId',D);
  let s={};
  const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const money=x=>Number(x||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const now=()=>new Date().toLocaleString('pt-BR');
  const css=document.createElement('style'); css.id='fusionProCss'; css.textContent=`
  body{padding:0!important;background:#020617!important;color:#e2e8f0!important;font-family:Inter,system-ui,sans-serif}
  main{padding:22px 28px!important;max-width:1600px;margin:auto}
  .fusion-top{position:sticky;top:0;z-index:10;display:flex;align-items:center;gap:8px;flex-wrap:wrap;padding:10px 0 14px;margin-bottom:22px;background:#020617;border-bottom:1px solid #1e293b}
  .fusion-top .brand{font-weight:900;font-size:14px;margin-right:10px;letter-spacing:.2px}.fusion-top .sub{font-size:10px;color:#64748b;margin-right:auto}
  .fusion-nav{display:flex;gap:7px;overflow:auto}.fusion-nav button{background:#0f172a;color:#94a3b8;border:1px solid #1e293b;padding:9px 13px;border-radius:8px;font-weight:800;white-space:nowrap;cursor:pointer;transition:.18s}.fusion-nav button:hover{border-color:#3b82f6;color:#fff}.fusion-nav .on{background:#2563eb;color:#fff;border-color:#3b82f6;box-shadow:0 4px 18px #2563eb33}
  .fusion-head{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.fusion-title{font-size:26px;font-weight:900;margin:0}.fusion-sub{font-size:12px;color:#64748b;margin-top:4px}
  .fusion-card{background:linear-gradient(145deg,#111c31,#0b1426);border:1px solid #1e293b;border-radius:13px;padding:17px;margin-bottom:16px;box-shadow:0 10px 30px #00000018}.fusion-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.fusion-k{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin:18px 0}.fusion-k .fusion-card{margin:0;position:relative;overflow:hidden}.fusion-k .fusion-card:after{content:'';position:absolute;right:-20px;top:-20px;width:70px;height:70px;border-radius:50%;background:#2563eb18}.fusion-k small{color:#94a3b8;font-size:11px}.fusion-k b{display:block;font-size:25px;margin-top:7px;color:#f8fafc}.kpi-blue{border-top:3px solid #3b82f6}.kpi-green{border-top:3px solid #22c55e}.kpi-orange{border-top:3px solid #f59e0b}.kpi-red{border-top:3px solid #ef4444}.kpi-purple{border-top:3px solid #a855f7}
  .fusion-btn{border:1px solid transparent;border-radius:8px;padding:9px 13px;font-weight:800;cursor:pointer;color:#fff;transition:.15s}.fusion-btn:hover{transform:translateY(-1px);filter:brightness(1.08)}.fg{background:#16a34a}.fb{background:#2563eb}.fo{background:#ea580c}.fp{background:#7c3aed}.fr{background:#dc2626}.fd{background:#334155}
  .fusion-input,.fusion-select,.fusion-text{box-sizing:border-box;width:100%;background:#020617!important;color:#e2e8f0!important;border:1px solid #334155!important;border-radius:8px;padding:10px}.fusion-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.fusion-form .full{grid-column:1/-1}
  .fusion-table{width:100%;border-collapse:separate;border-spacing:0;font-size:12px;overflow:hidden}.fusion-table th,.fusion-table td{padding:11px 10px;border-bottom:1px solid #1e293b;text-align:left}.fusion-table th{background:#0b1220;color:#94a3b8;font-size:10px;text-transform:uppercase;letter-spacing:.04em;position:sticky;top:0}.fusion-table tr:hover td{background:#ffffff03}
  .badge{display:inline-flex;align-items:center;padding:4px 8px;border-radius:999px;font-size:10px;font-weight:800}.b-ok{background:#16a34a22;color:#4ade80}.b-warn{background:#f59e0b22;color:#fbbf24}.b-bad{background:#ef444422;color:#f87171}.b-blue{background:#3b82f622;color:#60a5fa}.b-gray{background:#64748b22;color:#94a3b8}
  .activity{padding:11px 13px;background:#020617;border:1px solid #1e293b;border-radius:9px;margin:7px 0}.activity b{font-size:12px}.muted{color:#64748b;font-size:11px}.empty{padding:30px;text-align:center;color:#64748b}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.toolbar>*{max-width:260px}.modalx{position:fixed;inset:0;z-index:100;display:none;align-items:center;justify-content:center;background:#000b;padding:18px}.modalx.open{display:flex}.modalx>div{width:min(680px,100%);max-height:90vh;overflow:auto;background:#0b1426;border:1px solid #334155;border-radius:14px;padding:20px;box-shadow:0 25px 80px #000}.closex{background:transparent;color:#94a3b8;border:0;font-size:22px;cursor:pointer}.toastx{position:fixed;right:18px;bottom:18px;z-index:120;background:#0f172a;border:1px solid #334155;padding:12px 16px;border-radius:10px;box-shadow:0 15px 40px #000;display:none}.toastx.show{display:block}
  @media(max-width:1100px){.fusion-k{grid-template-columns:repeat(3,1fr)}}@media(max-width:800px){main{padding:14px!important}.fusion-grid,.fusion-form{grid-template-columns:1fr}.fusion-k{grid-template-columns:repeat(2,1fr)}.fusion-top .sub{display:none}}@media(max-width:520px){.fusion-k{grid-template-columns:1fr}.fusion-title{font-size:21px}}
  `; document.head.appendChild(css);
  const old=document.querySelector('aside'); if(old)old.style.display='none';
  const main=document.querySelector('main'); if(!main)return;
  let top=document.getElementById('fusionProTop'); if(top)top.remove(); top=document.createElement('div'); top.id='fusionProTop'; top.className='fusion-top';
  top.innerHTML=`<div class="brand">⚙️ PLATAFORMA MANUTENÇÃO 4.0</div><div class="sub">CMMS • Operação industrial sincronizada</div><div class="fusion-nav"></div><span class="badge b-blue">${D}</span>`; main.prepend(top);
  const nav=top.querySelector('.fusion-nav');
  const tabs=[['dashboard','📊 Dashboard & KPIs'],['equipamentos','🏭 Cadastro de Ativos'],['ordens','📋 Abertura de O.S.'],['estoque','📦 Peças & Almoxarifado'],['historico','🕘 Histórico & Relatórios']];
  const show=id=>{tabs.forEach(([x])=>{const el=q(x);if(el)el.style.display=x===id?'block':'none'});nav.querySelectorAll('button').forEach(b=>b.classList.toggle('on',b.dataset.id===id));window.scrollTo({top:0,behavior:'smooth'})};
  tabs.forEach(([id,t],i)=>{const b=document.createElement('button');b.textContent=t;b.dataset.id=id;b.onclick=()=>show(id);nav.appendChild(b)});
  const toast=m=>{let t=q('fusionToast');if(!t){t=document.createElement('div');t.id='fusionToast';t.className='toastx';document.body.appendChild(t)}t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)};
  const modal=(title,body,onSave)=>{let m=q('fusionModal');if(m)m.remove();m=document.createElement('div');m.id='fusionModal';m.className='modalx open';m.innerHTML=`<div><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:14px"><h3 style="margin:0;font-size:18px">${title}</h3><button class=closex>✕</button></div>${body}<div style="display:flex;justify-content:flex-end;gap:8px;margin-top:16px"><button class="fusion-btn fd closeBtn">Cancelar</button><button class="fusion-btn fb saveBtn">Salvar</button></div></div>`;document.body.appendChild(m);m.querySelectorAll('.closex,.closeBtn').forEach(x=>x.onclick=()=>m.remove());m.querySelector('.saveBtn').onclick=async()=>{try{await onSave(m);m.remove()}catch(e){toast('Erro: '+e.message)}}};
  const build=()=>{
    q('dashboard').innerHTML=`<div class=fusion-head><div><h2 class=fusion-title>Dashboard & KPIs</h2><div class=fusion-sub>Visão geral da operação e manutenção</div></div><button class="fusion-btn fb" onclick="fusionNewOS()">＋ Nova O.S.</button></div><div class=fusion-k><div class="fusion-card kpi-blue"><small>Disponibilidade</small><b id=xdisp>—</b></div><div class="fusion-card kpi-green"><small>OS abertas</small><b id=xopen>0</b></div><div class="fusion-card kpi-purple"><small>OS concluídas</small><b id=xdone>0</b></div><div class="fusion-card kpi-orange"><small>MTTR</small><b id=xmttr>0 min</b></div><div class="fusion-card kpi-red"><small>Custo acumulado</small><b id=xcost>R$ 0,00</b></div></div><div class=fusion-grid><div class=fusion-card><h3>Distribuição das manutenções</h3><canvas id=xc1 height=220></canvas></div><div class=fusion-card><h3>Falhas por categoria</h3><canvas id=xc2 height=220></canvas></div></div><div class=fusion-card><h3>Status operacional</h3><div id=xstatus></div></div><div class=fusion-card><h3>Últimas movimentações</h3><div id=xrecent></div></div>`;
    q('equipamentos').innerHTML=`<div class=fusion-head><div><h2 class=fusion-title>Cadastro de Ativos</h2><div class=fusion-sub>Controle de máquinas, horímetros e criticidade</div></div><button class="fusion-btn fb" onclick="fusionNewEq()">＋ Novo ativo</button></div><div class=fusion-card><div class=toolbar><input id=eqSearch class=fusion-input placeholder="🔍 Buscar equipamento..."></div><div style=overflow:auto><table class=fusion-table><thead><tr><th>Código</th><th>Máquina</th><th>Horímetro</th><th>Limite</th><th>Criticidade</th><th>Status</th><th>Ação</th></tr></thead><tbody id=xeql></tbody></table></div></div>`;
    q('ordens').innerHTML=`<div class=fusion-head><div><h2 class=fusion-title>Ordens de Serviço</h2><div class=fusion-sub>Abra, acompanhe e finalize intervenções</div></div><button class="fusion-btn fb" onclick="fusionNewOS()">＋ Abrir O.S.</button></div><div class=fusion-card><div class=toolbar><input id=osSearch class=fusion-input placeholder="🔍 Buscar OS, equipamento ou descrição..."><select id=osType class=fusion-select><option>TODOS</option><option>Preventiva</option><option>Corretiva</option><option>Preditiva</option></select><select id=osStatus class=fusion-select><option>TODOS</option><option>Pendente</option><option>Em Andamento</option><option>Concluída</option></select></div><div style=overflow:auto><table class=fusion-table><thead><tr><th>OS</th><th>Equipamento</th><th>Tipo</th><th>Prioridade</th><th>Status</th><th>Custo</th><th>Ação</th></tr></thead><tbody id=xol></tbody></table></div></div>`;
    q('estoque').innerHTML=`<div class=fusion-head><div><h2 class=fusion-title>Peças & Almoxarifado</h2><div class=fusion-sub>Controle de quantidade, custo e estoque mínimo</div></div><button class="fusion-btn fb" onclick="fusionNewPart()">＋ Nova peça</button></div><div class=fusion-card><div style=overflow:auto><table class=fusion-table><thead><tr><th>Código</th><th>Descrição</th><th>Qtd.</th><th>Mínimo</th><th>Custo unit.</th><th>Condição</th></tr></thead><tbody id=xpl></tbody></table></div></div>`;
    q('historico').innerHTML=`<div class=fusion-head><div><h2 class=fusion-title>Histórico & Relatórios</h2><div class=fusion-sub>Registro compartilhado entre os dispositivos</div></div><button class="fusion-btn fg" onclick="fusionExport()">⬇ Exportar CSV</button></div><div class=fusion-card><div class=toolbar><input id=hSearch class=fusion-input placeholder="🔍 Buscar no histórico..."></div><div style=overflow:auto><table class=fusion-table><thead><tr><th>Data</th><th>Equipamento</th><th>Evento</th><th>OS</th><th>Custo</th><th>Dispositivo</th></tr></thead><tbody id=xhl></tbody></table></div></div>`;
    ['eqSearch','osSearch','osType','osStatus','hSearch'].forEach(id=>q(id)?.addEventListener('input',render));
  };
  window.fusionNewEq=()=>modal('Novo ativo industrial',`<div class=fusion-form><input id=mcode class=fusion-input placeholder="Código do ativo" required><input id=mname class=fusion-input placeholder="Nome do equipamento" required><input id=mhor type=number class=fusion-input placeholder="Horímetro" value="0"><input id=mlim type=number class=fusion-input placeholder="Limite preventiva" value="500"><select id=mcrit class=fusion-select><option>Alta (Classe A)</option><option>Média (Classe B)</option><option>Baixa (Classe C)</option></select><input id=mloc class=fusion-input placeholder="Localização"></div>`,async()=>{await R.child('equipments').push().set({codigo:mcode.value,nome:mname.value,horimetro:+mhor.value,limite:+mlim.value,criticidade:mcrit.value,location:mloc.value,status:'Operacional',createdAt:firebase.database.ServerValue.TIMESTAMP,createdByDevice:D});toast('Ativo salvo no Firebase')});
  window.fusionNewOS=()=>modal('Abrir Ordem de Serviço',`<div class=fusion-form><input id=oeq class="fusion-input full" placeholder="Equipamento / ativo" required><textarea id=odesc class="fusion-text full" rows=4 placeholder="Descrição do serviço" required></textarea><select id=otype class=fusion-select><option>Preventiva</option><option>Corretiva</option><option>Preditiva</option></select><select id=opri class=fusion-select><option>Baixa</option><option selected>Média</option><option>Alta</option><option>Crítica</option></select><input id=otec class=fusion-input placeholder="Técnico responsável"><input id=ocat class=fusion-input placeholder="Categoria"><input id=ocost type=number min=0 value=0 class=fusion-input placeholder="Custo"></div>`,async()=>{const r=R.child('orders').push();await r.set({equipment:oeq.value,description:odesc.value,type:otype.value,priority:opri.value,technician:otec.value,category:ocat.value,cost:+ocost.value,status:'Pendente',createdAt:firebase.database.ServerValue.TIMESTAMP,createdByDevice:D});toast('O.S. criada com sucesso')});
  window.fusionNewPart=()=>modal('Nova peça / item de estoque',`<div class=fusion-form><input id=pcod class=fusion-input placeholder="Código"><input id=pname class=fusion-input placeholder="Descrição" required><input id=pqty type=number min=0 class=fusion-input placeholder="Quantidade" value="0"><input id=pmin type=number min=0 class=fusion-input placeholder="Estoque mínimo" value="2"><input id=pcost type=number min=0 step=.01 class=fusion-input placeholder="Custo unitário" value="0"><input id=punit class=fusion-input placeholder="Unidade" value="un"></div>`,async()=>{await R.child('parts').push().set({id:pcod.value,nome:pname.value,qtd:+pqty.value,min:+pmin.value,custo:+pcost.value,unit:punit.value,updatedAt:firebase.database.ServerValue.TIMESTAMP,updatedByDevice:D});toast('Peça adicionada ao estoque')});
  window.fusionFinish=async id=>{const x=s.orders?.[id];if(!x||x.status==='Concluída')return;await R.child('orders/'+id).update({status:'Concluída',completedAt:firebase.database.ServerValue.TIMESTAMP,completedByDevice:D});const h=R.child('history').push();await h.set({date:firebase.database.ServerValue.TIMESTAMP,equipment:x.equipment,event:'OS finalizada: '+x.description,orderId:id,cost:Number(x.cost||0),device:D});toast('O.S. finalizada e enviada ao histórico')};
  function render(){
    const os=Object.entries(s.orders||{}).map(([id,x])=>({...x,id})).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)); const eq=Object.entries(s.equipments||{}); const parts=Object.entries(s.parts||{}); const hist=Object.values(s.history||{}).sort((a,b)=>(b.date||0)-(a.date||0));
    const open=os.filter(x=>x.status!=='Concluída').length,done=os.length-open,cost=os.reduce((a,x)=>a+Number(x.cost||x.custoTotal||0),0),cor=os.filter(x=>(x.type||x.tipo)==='Corretiva'),downtime=cor.reduce((a,x)=>a+Number(x.time||x.tempo||0),0),mttr=cor.length?downtime/cor.length:0;
    const disp=eq.length?Math.max(0,100-(downtime/(eq.length*1440))*100):100;
    q('xdisp').textContent=disp.toFixed(1)+'%';q('xopen').textContent=open;q('xdone').textContent=done;q('xmttr').textContent=mttr.toFixed(1)+' min';q('xcost').textContent=money(cost);
    const ef=(q('eqSearch')?.value||'').toLowerCase();q('xeql').innerHTML=eq.filter(([id,e])=>!ef||`${e.codigo||id} ${e.nome||e.name||''}`.toLowerCase().includes(ef)).map(([id,e])=>{const h=Number(e.horimetro||0),l=Number(e.limite||Infinity),bad=h>=l;return `<tr><td><b>${esc(e.codigo||id.slice(-6))}</b></td><td>${esc(e.nome||e.name)}</td><td>${h} h</td><td>${isFinite(l)?l+' h':'—'}</td><td>${esc(e.criticidade||'—')}</td><td><span class="badge ${bad?'b-warn':'b-ok'}">${bad?'Preventiva vencida':esc(e.status||'Operacional')}</span></td><td><button class="fusion-btn fp" onclick="alert('Ativo: ${esc(e.codigo||id)}\n${esc(e.nome||e.name)}\nHorímetro: ${h}h')">QR / Detalhes</button></td></tr>`}).join('')||'<tr><td colspan=7 class=empty>Nenhum ativo encontrado.</td></tr>';
    const osf=(q('osSearch')?.value||'').toLowerCase(),ot=q('osType')?.value||'TODOS',ost=q('osStatus')?.value||'TODOS';q('xol').innerHTML=os.filter(x=>(!osf||`${x.id} ${x.equipment||''} ${x.description||''}`.toLowerCase().includes(osf))&&(ot==='TODOS'||x.type===ot)&&(ost==='TODOS'||x.status===ost)).map(x=>`<tr><td><b>#${esc(x.id.slice(-8))}</b></td><td>${esc(x.equipment)}</td><td>${esc(x.type)}</td><td><span class="badge ${x.priority==='Crítica'||x.priority==='Alta'?'b-bad':x.priority==='Média'?'b-warn':'b-gray'}">${esc(x.priority)}</span></td><td><span class="badge ${x.status==='Concluída'?'b-ok':'b-blue'}">${esc(x.status)}</span></td><td>${money(x.cost)}</td><td>${x.status!=='Concluída'?`<button class="fusion-btn fg" onclick="fusionFinish('${x.id}')">Finalizar</button>`:'✓'}</td></tr>`).join('')||'<tr><td colspan=7 class=empty>Nenhuma O.S. encontrada.</td></tr>';
    q('xpl').innerHTML=parts.map(([id,p])=>{const n=Number(p.qtd??p.qty??0),m=Number(p.min??2);return `<tr><td>#${esc(p.id||id.slice(-6))}</td><td>${esc(p.nome||p.name)}</td><td><b>${n}</b> ${esc(p.unit||'un')}</td><td>${m}</td><td>${money(p.custo??p.cost)}</td><td><span class="badge ${n<=m?'b-bad':'b-ok'}">${n<=m?'Reabastecer':'Suficiente'}</span></td></tr>`}).join('')||'<tr><td colspan=6 class=empty>Nenhuma peça cadastrada.</td></tr>';
    const hf=(q('hSearch')?.value||'').toLowerCase();q('xhl').innerHTML=hist.filter(h=>!hf||`${h.equipment||''} ${h.event||''} ${h.orderId||''}`.toLowerCase().includes(hf)).map(h=>`<tr><td>${h.date?new Date(h.date).toLocaleString('pt-BR'):'—'}</td><td>${esc(h.equipment)}</td><td>${esc(h.event)}</td><td>${esc(h.orderId||'—')}</td><td>${money(h.cost)}</td><td>${esc(h.device||'—')}</td></tr>`).join('')||'<tr><td colspan=6 class=empty>Nenhum registro.</td></tr>';
    q('xstatus').innerHTML=eq.map(([id,e])=>{const h=Number(e.horimetro||0),l=Number(e.limite||Infinity),bad=h>=l;return `<div class=activity><b>${esc(e.codigo||id)}</b> — ${esc(e.nome||e.name)} <span style=float:right class="badge ${bad?'b-warn':'b-ok'}">${bad?'Preventiva vencida':esc(e.status||'Operacional')}</span></div>`}).join('')||'<div class=empty>Nenhum equipamento cadastrado.</div>';
    q('xrecent').innerHTML=hist.slice(0,7).map(h=>`<div class=activity><b>${esc(h.event||'Manutenção registrada')}</b><div class=muted>${esc(h.equipment||'')} • ${h.date?new Date(h.date).toLocaleString('pt-BR'):''} • ${esc(h.device||'')}</div></div>`).join('')||'<div class=empty>Nenhuma movimentação.</div>';
    if(window.c1)window.c1.destroy();if(window.c2)window.c2.destroy();if(typeof Chart!=='undefined'){window.c1=new Chart(q('xc1'),{type:'doughnut',data:{labels:['Preventiva','Corretiva','Preditiva'],datasets:[{data:[os.filter(x=>x.type==='Preventiva').length,cor.length,os.filter(x=>x.type==='Preditiva').length],backgroundColor:['#3b82f6','#ef4444','#a855f7'],borderWidth:0}]},options:{responsive:true,plugins:{legend:{labels:{color:'#cbd5e1'}}}}});const cats=['Mecânica','Elétrica','Hidráulica','Pneumática','Outros'];window.c2=new Chart(q('xc2'),{type:'bar',data:{labels:cats,datasets:[{label:'Ocorrências',data:cats.map(c=>os.filter(x=>(x.category||'').toLowerCase().includes(c.toLowerCase())).length),backgroundColor:'#f59e0b',borderRadius:5}]},options:{responsive:true,plugins:{legend:{labels:{color:'#cbd5e1'}}},scales:{x:{ticks:{color:'#94a3b8'},grid:{display:false}},y:{ticks:{color:'#94a3b8'},grid:{color:'#1e293b'}}}}})}
  }
  window.fusionExport=()=>{const rows=Object.entries(s.orders||{}).map(([id,x])=>({...x,id}));if(!rows.length)return toast('Não há OS para exportar.');const cell=v=>{let z=String(v??'').replace(/[\r\n]+/g,' ');if(/^[=+\-@]/.test(z))z="'"+z;return '"'+z.replace(/"/g,'""')+'"'};let csv='\uFEFFOS;Equipamento;Tipo;Prioridade;Status;Técnico;Categoria;Tempo (min);Custo (R$);Descrição;Dispositivo\n';rows.forEach(x=>csv+=[x.id,x.equipment,x.type,x.priority,x.status,x.technician,x.category,x.time||0,Number(x.cost||0).toFixed(2).replace('.',','),x.description,x.createdByDevice].map(cell).join(';')+'\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='Relatorio_Manutencao_4.0_'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),500);toast('Relatório exportado com sucesso')};
  build();show('dashboard');R.on('value',snap=>{s=snap.val()||{};const st=q('firebaseStatus');if(st)st.textContent='Firebase conectado';render()},err=>{const st=q('firebaseStatus');if(st)st.textContent='Firebase: erro';console.error(err)});
})();